
<?php 
	// path
	define("ROOT",dirname(__DIR__));
	define("MODElS",ROOT.DIRECTORY_SEPARATOR."mvc".DIRECTORY_SEPARATOR."models".DIRECTORY_SEPARATOR);
	define("VIEWS",ROOT.DIRECTORY_SEPARATOR."mvc".DIRECTORY_SEPARATOR."views".DIRECTORY_SEPARATOR);
	define("CONTROLLERS",ROOT.DIRECTORY_SEPARATOR."mvc".DIRECTORY_SEPARATOR."controllers".DIRECTORY_SEPARATOR);
	define("CORE",ROOT.DIRECTORY_SEPARATOR."mvc".DIRECTORY_SEPARATOR."core".DIRECTORY_SEPARATOR);
	define("FILES",ROOT.DIRECTORY_SEPARATOR."mvc".DIRECTORY_SEPARATOR."files".DIRECTORY_SEPARATOR);
	// database
	define("DB_HOST", "localhost");
	define("DB_USER", "root");
	define("DB_PASS", "");
	define("DB_NAME", "iot_project_improve");

